import { useEffect, useState } from 'react';
import { BarChart3, Clock3, Eye, Globe2, Loader2, Menu, MessageCircle, Users, X } from 'lucide-react';
import { Link, useLocation } from 'wouter';
import { supabase } from '@/lib/supabase';

type Country = { code: string; country: string; visitors: number };
type City = { countryCode: string | null; country: string; city: string; visitors: number };
type Recent = { createdAt: string; eventType: string; ref: string; path: string; countryCode: string | null; country: string; city: string | null; productId: string | null; durationSeconds: number | null; scrollDepth: number | null };
type Analytics = { periodDays: number; totalVisits: number; uniqueVisitors: number; todayVisits: number; browsedVisitors: number; engagedVisitors: number; bouncedVisitors: number; productViews: number; whatsappClicks: number; whatsappVisitors: number; avgEngagementSeconds: number; countries: Country[]; cities: City[]; refs: { ref: string; count: number }[]; recent: Recent[] };

import { brandAssets } from '@/lib/brand';
const logo = brandAssets.logo;
const eventLabel: Record<string, string> = { site_visit: 'Opened catalogue', product_view: 'Viewed product', product_click: 'Opened product', whatsapp_click: 'Clicked WhatsApp', engaged_visit: 'Stayed engaged', scroll_depth: 'Scrolled', session_end: 'Left catalogue' };
function formatDate(value: string) { return new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value)); }
function formatDuration(seconds: number) { if (!seconds) return '—'; if (seconds < 60) return `${seconds}s`; return `${Math.floor(seconds / 60)}m ${seconds % 60}s`; }
function cleanError(raw: string) { try { const parsed = JSON.parse(raw); return parsed.error || parsed.message || raw; } catch { return raw || 'Could not load analytics.'; } }

function Shell({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false); const [location] = useLocation();
  const nav = [['/admin/dashboard','Overview'],['/admin/upload','Upload'],['/admin/review','Review'],['/admin/products','Products'],['/admin/collections','Collections'],['/admin/catalogue','Publish & Share'],['/admin/analytics','Analytics'],['/admin/settings','Settings']];
  return <div className="min-h-[100dvh] bg-[var(--lh-ivory)] text-[var(--lh-ink)]">
    <aside className={`fixed inset-y-0 left-0 z-50 w-[264px] bg-[var(--lh-burgundy)] px-5 py-6 text-[var(--lh-ivory-light)] transition-transform lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="flex items-center justify-between"><div className="rounded-xl bg-[var(--lh-ivory-light)] p-2"><img src={logo} alt="THE BRAND STORE" className="h-8 w-auto" /></div><button onClick={() => setOpen(false)} className="lg:hidden"><X size={20} /></button></div>
      <nav className="mt-8 space-y-1">{nav.map(([href, label]) => <Link key={href} href={href} onClick={() => setOpen(false)} className={`block rounded-xl px-3 py-3 text-sm ${location === href ? 'bg-white/10 text-[var(--lh-champagne)]' : 'text-white/75 hover:bg-white/5 hover:text-white'}`}>{label}</Link>)}</nav>
    </aside>
    <div className="lg:pl-[264px]"><header className="sticky top-0 z-40 flex h-[66px] items-center justify-between border-b border-[var(--lh-border)] bg-[color:var(--lh-ivory)]/95 px-5 backdrop-blur sm:px-8"><button onClick={() => setOpen(true)} className="lg:hidden"><Menu size={21} /></button><span className="hidden text-[10px] font-semibold uppercase tracking-[.18em] text-[var(--lh-muted-ink)] lg:block">THE BRAND STORE Collection OS</span><Link href="/catalogue" className="text-xs font-semibold text-[var(--lh-burgundy)]">View catalogue</Link></header>{children}</div>
  </div>;
}

export default function AdminAnalyticsV2() {
  const [token, setToken] = useState<string | null>(null); const [data, setData] = useState<Analytics | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async (accessToken: string) => { setLoading(true); setError(''); try { const response = await fetch('/api/analytics', { headers: { Authorization: `Bearer ${accessToken}` } }); if (!response.ok) throw new Error(cleanError(await response.text())); setData(await response.json()); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load analytics.'); } finally { setLoading(false); } };
  useEffect(() => { void supabase?.auth.getSession().then(({ data }) => { const accessToken = data.session?.access_token || null; setToken(accessToken); if (accessToken) void load(accessToken); else { setError('Admin session is required.'); setLoading(false); } }); }, []);
  if (loading) return <Shell><main className="mx-auto max-w-[1280px] px-5 py-10"><Loader2 className="animate-spin text-[var(--lh-burgundy)]" /></main></Shell>;
  return <Shell><main className="mx-auto max-w-[1280px] px-5 py-8 sm:px-8 lg:py-10">
    <div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="lh-label">Audience</p><h1 className="mt-2 font-display text-4xl sm:text-5xl">Analytics</h1><p className="mt-2 max-w-2xl text-sm text-[var(--lh-muted-ink)]">Understand whether clients opened, browsed and engaged with the catalogue. Country and city are approximate Cloudflare geolocation.</p></div><button disabled={!token} onClick={() => token && void load(token)} className="lh-secondary-action rounded-full px-4 py-2.5 text-xs font-semibold">Refresh</button></div>
    {error && <div className="mb-5 rounded-xl border border-[var(--lh-border)] bg-[var(--lh-ivory-light)] px-4 py-3 text-xs text-[var(--lh-muted-ink)]">{error}</div>}
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
      <div className="rounded-2xl bg-[var(--lh-burgundy)] p-5 text-[var(--lh-ivory-light)]"><Users size={18} className="text-[var(--lh-champagne)]"/><p className="mt-5 text-[9px] font-semibold uppercase tracking-[.16em] text-white/55">Unique visitors</p><p className="mt-2 font-display text-4xl">{data?.uniqueVisitors || 0}</p><p className="mt-2 text-xs text-white/50">Distinct browsers/devices</p></div>
      <div className="rounded-2xl border border-[var(--lh-border)] bg-[var(--lh-ivory-light)] p-5"><Eye size={18} className="text-[var(--lh-burgundy)]"/><p className="mt-5 text-[9px] font-semibold uppercase tracking-[.16em] text-[var(--lh-muted-ink)]">Browsed</p><p className="mt-2 font-display text-4xl">{data?.browsedVisitors || 0}</p><p className="mt-2 text-xs text-[var(--lh-muted-ink)]">Viewed at least one product</p></div>
      <div className="rounded-2xl border border-[var(--lh-border)] bg-[var(--lh-ivory-light)] p-5"><Clock3 size={18} className="text-[var(--lh-burgundy)]"/><p className="mt-5 text-[9px] font-semibold uppercase tracking-[.16em] text-[var(--lh-muted-ink)]">Engaged</p><p className="mt-2 font-display text-4xl">{data?.engagedVisitors || 0}</p><p className="mt-2 text-xs text-[var(--lh-muted-ink)]">20s+ active engagement</p></div>
      <div className="rounded-2xl border border-[var(--lh-border)] bg-[var(--lh-ivory-light)] p-5"><MessageCircle size={18} className="text-[var(--lh-burgundy)]"/><p className="mt-5 text-[9px] font-semibold uppercase tracking-[.16em] text-[var(--lh-muted-ink)]">WhatsApp</p><p className="mt-2 font-display text-4xl">{data?.whatsappClicks || 0}</p><p className="mt-2 text-xs text-[var(--lh-muted-ink)]">Clicks to enquire</p></div>
    </div>

    <div className="mt-5 grid gap-5 lg:grid-cols-[1.05fr_.95fr]">
      <section className="lh-panel rounded-2xl p-6 sm:p-7"><div className="flex items-end justify-between gap-3"><div><p className="lh-label">Geography</p><h2 className="mt-2 font-display text-2xl">Visitors by country</h2></div><Globe2 size={20} className="text-[var(--lh-burgundy)]"/></div><div className="mt-5 space-y-2">{(data?.countries || []).map((item) => <div key={item.code} className="flex items-center justify-between rounded-xl bg-[var(--lh-ivory)] px-4 py-3 text-sm"><span>{item.country}</span><strong>{item.visitors}</strong></div>)}{!(data?.countries || []).length && <p className="text-sm text-[var(--lh-muted-ink)]">No visitors recorded yet.</p>}</div></section>
      <section className="lh-panel rounded-2xl p-6 sm:p-7"><p className="lh-label">Geography</p><h2 className="mt-2 font-display text-2xl">Approximate cities</h2><div className="mt-5 space-y-2">{(data?.cities || []).slice(0, 12).map((item) => <div key={`${item.countryCode}-${item.city}`} className="flex items-center justify-between rounded-xl bg-[var(--lh-ivory)] px-4 py-3 text-sm"><span>{item.city}<small className="ml-2 text-[10px] text-[var(--lh-muted-ink)]">{item.country}</small></span><strong>{item.visitors}</strong></div>)}{!(data?.cities || []).length && <p className="text-sm text-[var(--lh-muted-ink)]">No city data yet.</p>}</div></section>
    </div>

    <div className="mt-5 grid gap-5 lg:grid-cols-3">
      <section className="rounded-2xl bg-[var(--lh-ivory-deep)] p-6"><p className="lh-label">Catalogue behaviour</p><div className="mt-5 space-y-4 text-sm"><div className="flex justify-between"><span>Opened</span><strong>{data?.uniqueVisitors || 0}</strong></div><div className="flex justify-between"><span>Browsed products</span><strong>{data?.browsedVisitors || 0}</strong></div><div className="flex justify-between"><span>Stayed 20s+</span><strong>{data?.engagedVisitors || 0}</strong></div><div className="flex justify-between"><span>Opened and left</span><strong>{data?.bouncedVisitors || 0}</strong></div><div className="flex justify-between"><span>Product views</span><strong>{data?.productViews || 0}</strong></div><div className="flex justify-between"><span>Avg. engaged time</span><strong>{formatDuration(data?.avgEngagementSeconds || 0)}</strong></div></div></section>
      <section className="lh-panel rounded-2xl p-6"><p className="lh-label">Visits</p><h2 className="mt-2 font-display text-2xl">Traffic</h2><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><span>Today</span><strong>{data?.todayVisits || 0}</strong></div><div className="flex justify-between"><span>Last {data?.periodDays || 30} days</span><strong>{data?.totalVisits || 0}</strong></div><div className="flex justify-between"><span>WhatsApp visitors</span><strong>{data?.whatsappVisitors || 0}</strong></div></div><div className="mt-6 border-t border-[var(--lh-border)] pt-5"><p className="lh-label">Link source</p>{(data?.refs || []).slice(0, 5).map((item) => <div key={item.ref} className="mt-2 flex justify-between text-xs"><span className="truncate pr-4">{item.ref}</span><strong>{item.count}</strong></div>)}</div></section>
      <section className="rounded-2xl bg-[var(--lh-ivory-deep)] p-6"><p className="lh-label">Recent activity</p><div className="mt-5 space-y-3">{(data?.recent || []).slice(0, 9).map((item, index) => <div key={`${item.createdAt}-${index}`} className="border-b border-[var(--lh-border)] pb-3 last:border-0"><div className="flex items-start justify-between gap-3"><span className="text-xs font-semibold">{eventLabel[item.eventType] || item.eventType}</span><span className="text-[10px] text-[var(--lh-muted-ink)]">{formatDate(item.createdAt)}</span></div><p className="mt-1 text-[10px] text-[var(--lh-muted-ink)]">{item.city ? `${item.city}, ` : ''}{item.country} · {item.path}</p></div>)}</div></section>
    </div>
    <p className="mt-5 text-xs leading-5 text-[var(--lh-muted-ink)]">Country and city are approximate, based on Cloudflare request geolocation. This tracker does not collect names, phone numbers or exact street addresses. Unique visitors are approximate distinct browsers/devices.</p>
  </main></Shell>;
}
